### ISSUE TITLE
CoreOS support

### ISSUE THREAD

**Issue by pmarsi** [inercia/terraform-provider-kubeadm#1]
Hi @inercia ,
I'm working on a project to create a k8s cluster in a baremetal servers. Your project could help me a lot to deploy a cluster, but I have some doubts...

1. is there support for coreOS OS?
2. I will use ssh-connections as a providers, is it possible right?

Thank you in advance

**Comment by inercia** [comment]
Hi @pmarsi. I have not tried CoreOS in my tests so I don't really know if it will work, but I can foresee some problems because of differences of CoreOS. The `kubeadm-provider` has an auto-installation script that tries to download and install `kubeadm` and it currently does not recognize CoreOS, but maybe you could try to create a installation script like:

```bash
#!/bin/sh
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
# make sure /opt/bin is in the default PATH
mkdir -p /opt/bin
cd /opt/bin
curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
chmod +x {kubeadm,kubelet,kubectl}
```

and then use this script for installing kubeadm:

```hcl
provisioner "kubeadm" {
   ...
   install {
      script = "myscript"
   }
}
```

Once `kubeadm` is available in the remote machine, everything is executed with the SSH connection created by Terraform, so you shouldn't have any problem...

Let me know how it goes...

**Comment by pmarsi** [comment]
Hi again,

I tried what you told me above and my installation script works fine...kubeadm is installed properly...but I need to make some changes...
1. First of all I need to change the target directory of kubelet.service, from /usr/lib/systemd/system to /etc/systemd/system

2. Is it possible to change kubernetes version? from 1.14.1 to 1.15.0...maybe I can do this change through terraform variables...

Thanks!

**Comment by inercia** [comment]
Hi @pmarsi. I will investigate the `kubelet.service` installation directory, because you are probably right and  `/etc/systemd/system` is a better target directory. Regarding the installation script, I'm improving it these days, I will try to add some configuration options for changing the version, but it also depends on the packages available on the repository (ie, maybe only 15.0 packages are available).

**Comment by pmarsi** [comment]
Hi @inercia. It seems that in CoreOS the /usr partition is read-only by design, because of that we need to use /etc for service files...

I made some scripts to install kubeadm in coreOS with differents requirements, so that I can share with you this information...

**Comment by inercia** [comment]
[This](https://github.com/inercia/terraform-provider-kubeadm/blob/master/internal/assets/static/kubeadm-setup.sh) is the script we currently use for auto-installing `kubeadm`. In order to support CoreOS, I guess we would need 1) some kind of fingerprint for knowing we are running the script in CoreOS (we use some keyfiles for other distros, like `/etc/debian_version` for debian) 2) some CoreOS-specific installation code.

**Comment by pmarsi** [comment]
yes, I've just to check the script and I think that could be possible to add all the necessary for coreOS.

I have another question...this provider allows to install the K8S cluster in HA?

**Comment by inercia** [comment]
> yes, I've just to check the script and I think that could be possible to add all the necessary for coreOS.

I will add some configuration arguments for customizing the insallation path for things like the service file. This will make things easier...

> I have another question...this provider allows to install the K8S cluster in HA?

I'm working on that in the `multi-master` branch. It should be ready in the next few days. As a side effect, the new code will require to change all the `data` declarations to `resource`...

Take into account that the new code will be able to create multiple masters but it will be user's responsability to create some load balancer that redirects traffic to one of these masters. The good thing is that, if this LB is created from Terraform, you will be able to get the certificates from the `kubeadm` resource and do SSL termination in your LB.
